language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"

env:
  global:
    - secure: "RKs9WOSenUXaGMCMjGQ1qjzSbVXpPUU6+AaEMakY19LT5os/ZDB6rUaPtkuL/PKSBgj2RBeojAOS70HBRkNJWV5ZjkYVbz+Jp7dichmLwx1OQ/Ax5fAO9r7YMqbOBHidoXBmKsjs7mYWoXKmjg8b5DVXHCMDgs9e9NIwDVqr3z0="
    - secure: "LjYwAfqGvi7pv4mOcX9K2Aekcz58CS0B5xNx8Rz70944arMqASgJQwsN53AZgc2wGg54E322jFm3xNEx/muN6nevMXnG14UaNcjylvDWEHk/OWfaQR/30uuPYXd0fjrfHAo8Q5W2oi41Il6WFFMka76LZ8sxXAeyZxQ8hnsd6ZQ="

before_install:
  - travis_retry pip install codecov
  - travis_retry curl -L -o travis_after_all.py https://raw.github.com/jmcarp/travis_after_all/master/travis_after_all.py
  - travis_retry curl -L -o cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.3&source=github-rel"
  - tar xzvf cf.tgz
  - export PATH=.:$PATH

before_script:
  - travis_retry pip install -U pip wheel
  - travis_retry pip install -r requirements.txt

  # Use production version of node.js
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.5.0
  - nvm use v5.5.0

  - travis_retry npm install
  - npm run build

script:
  - py.test
  - npm run test-single

after_success:
  # Deploy to appropriate Cloud Foundry space after all builds succeed
  # See `tasks.deploy` for details
  - if [[ $TRAVIS_PULL_REQUEST = 'false' ]]; then invoke deploy --branch $TRAVIS_BRANCH --yes; fi;
  - codecov --file .coverage --file coverage/coverage.json
