language: python

sudo: false

cache: pip

python:
  - "3.4"

env:
  global:
    - secure: "Waa09XB9IG1H3iB2LPXhq53j7IVElUaZf6VIc1V76ahqdlbfHuz36LoV4XfehPP6R6sT35nPFKXmr1wf5tMDyOP2CNIvu88M1beSTVC4lpSRPB1YQ9/ISTjs4srzlZKSKMmwuiHafE52POqrtf4sbtsRhtx+UdG10JQlliROUuo=" # FEC_CF_USERNAME
    - secure: "MfxUIgD2ozMtl4qG14qkKs6fFcnEyVgmOAOLNoQNO6xFpinBcZ7RFdDAcnSSy69PxUhHdYV4+dq5GRKb+TLCTMAypyPOG618w1A2482ZxlCL0quHedIMv1eRzDuBojl/O3ur6FrPbdrO42K2cy3OO4zzLQjlHfcPNywYZpKoBlo=" # FEC_CF_PASSWORD

before_script:
  - travis_retry pip install -U pip wheel
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements.test.txt


  # Use production version of node.js
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.5.0
  - nvm use v5.5.0

  - travis_retry npm install
  - npm run build

script:
  - py.test
  - npm run test-single

after_success:
  - travis_retry pip install codecov
  - codecov

before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --yes
  on:
    all_branches: true
