language: python

sudo: false

cache: pip

python:
  - "3.4"

addons:
  postgresql: "9.4"

env:
  global:
    - FEC_WEB_TEST="true"
    - FEC_SELENIUM_DRIVER="remote"
    - secure: "cmEueYaeTjqjnql7Vfk/qeZCIMfQRZLsEIA1WackpB5PQJxTAXfTFN6zq4r1LgYTxoOLGFi8s9a3zUJpJ7Nz+IYTEult/ehyW4mqbcYE1zodGDb55AllkmlvdYPbxKf0dJvGnMpcIqvgtAsKHGogOmBGEEc0uoiV3FFx1GvKCnM="
    - secure: "HjtrA4/I9b8m8ySCyL4VjJMmFyuYWrvZKWVSQFMCN7CklLXbn+UBdUl41Dk5ZUKijBZpLmrC4RSEJh8bFO6n0IbEvpGsmdL1FgqhBekPc1jfvzbOzjRvpKYuXtyzQcPv+FpBGXo9NydSh2OqEyNms2YBk9tZkRnhu/6G+10385o="
    - secure: "ChKakRzKKt9zXEundwZK3HIcsKk4T7TUyGZp1gVFs0AbAUwcKB846k2BocP8um77SNzcGVAma8fa0CBX8bR03YNl8Ko8zPWzvqqqj6n0gkSEYWbP7HEWV+tGAD2PCYcItfU409Mbzgv6E2BfGjsGEroX3nuHnMK176NjxrUb6gc="
    - secure: "F45t8tPX/Zdih2ZlT9wJVWtyJcxGwe1jtt6u136ASA/dHRyjg3lQfbUJcJiZG7Im3LTsgaAMnwSHOTWdIy5Ym/GKv58W8nyMC6IuNEsycosg6GE+/n8W4bBa8APMM5DqBkwsV2AbVzYiH9ktfs63Wg0HHsuWQp0F5yLndNKscGI="

# This matrix runs n+1 jobs: one for each in `include`, and one with no non-global
# environment variables set. This allows the build that does not use Sauce Labs
# to run without a tunnel to Sauce.
matrix:
  include:
    - env: FEC_SAUCE_BROWSER=chrome
      addons: &addons
        sauce_connect: true
        postgresql: "9.4"
      python: "3.4"
    - env: FEC_SAUCE_BROWSER=firefox
      addons: *addons
      python: "3.4"

before_install:
  - travis_retry pip install codecov
  - travis_retry curl -L -o travis_after_all.py https://raw.github.com/jmcarp/travis_after_all/master/travis_after_all.py
  - travis_retry curl -L -o cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.3&source=github-rel"
  - tar xzvf cf.tgz
  - export PATH=.:$PATH

before_script:
  # Set up environment
  - |
      if [[ $TRAVIS_BRANCH = 'master' ]]; then
        export FEC_BRANCH=master
        else export FEC_BRANCH=develop
      fi

  # Install web app and run in background
  - travis_retry pip install -r requirements.txt
  - travis_retry npm install
  - travis_retry npm install -g gulp
  - npm run build
  - python __init__.py &

  # Install API and run in background
  - travis_retry git clone https://github.com/18F/openFEC
  - cd openFEC
  - git checkout $FEC_BRANCH
  - psql -c 'create database cfdm_test' -U postgres
  - pg_restore --dbname cfdm_test data/subset.dump --no-acl --no-owner
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -U git+https://github.com/marshmallow-code/marshmallow-sqlalchemy@dev
  - travis_retry pip install marshmallow==2.0.0b4
  - python manage.py update_all --processes 1
  - python manage.py runserver &
  - cd ..

script:
  # Run Python unit tests
  - if [[ -z $FEC_SAUCE_BROWSER ]]; then py.test; fi
  # Run Javascript unit tests
  - if [[ -z $FEC_SAUCE_BROWSER ]]; then npm test; fi
  # Run Selenium tests if not pull request
  - if [[ $TRAVIS_PULL_REQUEST = 'false' && ! -z $FEC_SAUCE_BROWSER  ]]; then py.test --selenium; fi

after_success:
  # Deploy to appropriate Cloud Foundry space after all builds succeed
  # See `tasks.deploy` for details
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [[ $BUILD_LEADER = 'YES' && $TRAVIS_PULL_REQUEST = 'false' ]]; then
        if [[ $BUILD_AGGREGATE_STATUS = 'others_succeeded' ]]; then
          echo "All builds passed; deploying..."
          invoke deploy --branch $TRAVIS_BRANCH --yes
        else
          echo "One or more builds failed; skipping deploy"
        fi
      fi
  - if [[ $BUILD_LEADER = 'YES' ]]; then codecov; fi
