python: "3.4"
before_script:
    - python __init__.py
install:
    - sudo pip install -r requirements.txt
script:
    - cd openfecwebapp
    - cp example_config.py local_config.py
    - cd tests
    - nosetests
