language: python

sudo: false

cache: pip

python:
  - "3.4"

env:
  global:
    - secure: "RKs9WOSenUXaGMCMjGQ1qjzSbVXpPUU6+AaEMakY19LT5os/ZDB6rUaPtkuL/PKSBgj2RBeojAOS70HBRkNJWV5ZjkYVbz+Jp7dichmLwx1OQ/Ax5fAO9r7YMqbOBHidoXBmKsjs7mYWoXKmjg8b5DVXHCMDgs9e9NIwDVqr3z0="
    - secure: "LjYwAfqGvi7pv4mOcX9K2Aekcz58CS0B5xNx8Rz70944arMqASgJQwsN53AZgc2wGg54E322jFm3xNEx/muN6nevMXnG14UaNcjylvDWEHk/OWfaQR/30uuPYXd0fjrfHAo8Q5W2oi41Il6WFFMka76LZ8sxXAeyZxQ8hnsd6ZQ="

before_script:
  - travis_retry pip install -U pip wheel
  - travis_retry pip install -r requirements.txt

  # Use production version of node.js
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.5.0
  - nvm use v5.5.0

  - travis_retry npm install
  - npm run build

script:
  - py.test
  - npm run test-single

after_success:
  - travis_retry pip install codecov
  - codecov

before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community

deploy:
  provider: script
  script: invoke deploy --branch $TRAVIS_BRANCH --yes
  on:
    all_branches: true
