language: python
sudo: false
cache: pip
python:
- '3.4'
env:
  global:
  - secure: U8r+y8ScnAP/m0AOjYjqX90Wf9SWw5VGv+UXjnF/P6ypQl1dUAyDMXitw0B7XHjqmRP5xATcLGwL3IzFfowb8YFhVKSsO9h1pgpmkCGOhxxqp2jh978nU6df3SdbPmEvPlZaoBsLDVqRMHUPOyDLbaPN6iQtdbRcQhhE+zRcHT8= # dev user name
  - secure: X1yp0ohu6eZyaw+ybLWYiyTYFemHBUDHeSb8g+SGPxRZRhqt8l/GwElRxwGzZOviPaJ4qwZ7jUUJHN1CPfbSahV3amTXQ1AhAn3g+hZyoqHc1BifuHYBY8rhfthvI1PjGAOT7vnZoD839Oxw4TMA5R/O9l6JT9GG5hGs8SDqOak= # dev password
  - secure: DBxyNarMwmaJvDYExt5edNbaF3ON0JfCxYexVpqqS2dUTw4K87pV7IbPbQM7ZP54wf70Y6SBGjXpFG+0g248hjA1xz0okKRxB6MW3cq8591daUOFJ449zooHPCEVfzk4e6R6eubZhf2SPreFsmo5x1yjDYeoe8WPjuSIzj7Ky/M= # stage user name
  - secire: DGRlQecmn/UP1f9QM3vY2gXbPbME1G6qyUaXPr3FYVWpoLLqh9WmJuO9gieyP/ad2Kt+Kd7IcLglsQQo4UPXxeGYiFAG/XzZBn7ECJfzFtm9rgAmIbWUe1AmJ40l72WrW+eCiz8JOyPPx8VFv76+ytp7FETCQCsZi8o/HGfK9aU= # stage password
before_script:
- travis_retry pip install -U pip wheel
- travis_retry pip install -r requirements.txt
- travis_retry pip install -r requirements.test.txt
- ". $HOME/.nvm/nvm.sh"
- nvm install v5.5.0
- nvm use v5.5.0
- travis_retry npm install
- npm run build
script:
- py.test
- npm run test-single
after_success:
- travis_retry pip install codecov
- codecov
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
- tar xzvf $HOME/cf.tgz -C $HOME
- travis_retry cf install-plugin autopilot -f -r CF-Community
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --login True --yes
  on:
    all_branches: true
dd:
  secure: QkdjjW7fk4elNwOfduPMPLAv03WpyR1P65C0TiYhbZpOS0ONL1oRSaN4l+5dSvNG0wlinT3U7pBBsMaW+Pi+MH0+1ONbyc4eAF6ono4D4uaBvPq4zPe+y/y6TWCEiE+PrRvsXynvn6Hph8i2WHC9lbu4RzVhiQrvPaGJy6wY4kA=
