python: "3.4"
before-script:
    - cd openfecwebapp
    - cp example_config.py local_config.py
install:
    - sudo pip install -r requirements.txt
script:
    - cd openfecwebapp/tests
    - nosetests -a '!selenium'
