language: python

python:
  - "3.4"

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
    - cd openfecwebapp
install:
    - pip install -r requirements.txt
script:
    - cd tests
    - nosetests -a '!selenium'
