language: python

python:
  - "3.4"

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  sauce_connect: true
  postgresql: "9.4"

env:
  global:
    - FEC_WEB_TEST: true
    - FEC_SELENIUM_DRIVER: remote
    - SQLA_CONN: "postgresql://:@/cfdm_test"
    - secure: SQfanR6GI/1i4v7XPEKT26mKjd1BT/Qt1/5fjrhEIiA4PL2ZWnvArBmcKeq3q3CcVy2KQDTUr4vvPKbo4HGAw1EcUvnJ5lF6v3h0FmZ/bhMdkHk1e/UvfIVjOm0mEO80FDiXRcWEiYgY/Z4LwJ1l2iNC45j/1Odacj9I3fOdteY=
    - secure: aXkcjh6AHi1MnY1vZ5Nu8/8OexUZ4n8ul5hrM9iex0QdJAm4AoxF0idHybinTAAL7/gSEineX1to6GC3GVnAV/f/FU1mo8sjt0hvwTAx8b+ONR0M0sJW2KrPJRABQK4Dtxu+PQkE4Qim0GaJQ6LBJwTAB+HiegYymqrUFSV5tm0=
  matrix:
    - FEC_SAUCE_BROWSER: chrome
    - FEC_SAUCE_BROWSER: firefox

before_script:
  # Install web app and run in background
  - pip install -r requirements.txt
  - npm install
  - npm install -g browserify
  - npm run build
  - python __init__.py &

  # Install API and run in background
  - git clone https://github.com/18F/openFEC
  - cd openFEC
  - psql -c "create database cfdm_test" -U postgres
  - md5sum data/cfdm_test.pgdump.sql
  - psql -f data/cfdm_test.pgdump.sql -U postgres cfdm_test
  - psql -c "SELECT count(*) FROM dimcand" -U postgres cfdm_test
  - pip install -r requirements.txt
  - python manage.py update_schemas
  - python manage.py runserver &
  - cd ..

script:
  - nosetests openfecwebapp/tests
