language: python

python:
  - "3.4"

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  postgresql: "9.4"
  sauce_connect: true

env:
  global:
    - FEC_WEB_TEST: "true"
    - FEC_SELENIUM_DRIVER: "remote"
    - secure: "SKKeJG+Pc0xFyq0++/Cf0fMO4fZlK1H3CgedSGiQhwl3Rsh8QgXBhH+/YwWYAozmUNPkJCEuDdB2A1trBEPqkghAnjNdOXu2mwo5ANweu8M/HdafeeDP2klHB7bIieJ5GhUfrZ1/D/nVcE86mePFlx6Ymjdg2DtNUYBIWFs2xPs="
    - secure: "UK4kK8mrj0AsYqL7ohK9wKMCTVSK0phyNw7sW2BynRJYTU3Xi073+m8mGiCvHGEULvriCtuysCsbh5iNUz5VQ/4RBQVOJdugzbWjbwEUzb6w1W5pXvwCRUufhGcr98odfNE09pZicfL0YjH84w/dqrlC3leeyaoF7bFqpaKWwqs="
  matrix:
    - FEC_SAUCE_BROWSER: "false"
    - FEC_SAUCE_BROWSER: "chrome"
    - FEC_SAUCE_BROWSER: "firefox"

before_script:
  # Set up environment
  - if [[ $TRAVIS_BRANCH = 'master' ]]; then export FEC_BRANCH=master; fi
  - if [[ $TRAVIS_BRANCH != 'master' ]]; then export FEC_BRANCH=develop; fi

  # Install web app and run in background
  - pip install -r requirements.txt
  - npm install
  - npm install -g browserify
  - gem install sass
  - npm run build
  - python __init__.py &

  # Install API and run in background
  - git clone https://github.com/18F/openFEC
  - cd openFEC
  - git checkout $FEC_BRANCH
  - psql -c 'create database cfdm_test' -U postgres
  - psql -f data/subset.sql cfdm_test -U postgres
  - pip install -r requirements.txt
  - python manage.py update_schemas
  - python manage.py runserver &
  - cd ..

script:
  # Run unit tests
  - if [[ $FEC_SAUCE_BROWSER = 'false' ]]; then py.test openfecwebapp/tests; fi
  # Run Selenium tests if not pull request
  - if [[ $TRAVIS_PULL_REQUEST = 'false' && $FEC_SAUCE_BROWSER != 'false' ]]; then py.test openfecwebapp/tests --selenium; fi
