language: python
sudo: false
cache: pip
python:
  - "3.5"
env:
  global:
    - secure: U8r+y8ScnAP/m0AOjYjqX90Wf9SWw5VGv+UXjnF/P6ypQl1dUAyDMXitw0B7XHjqmRP5xATcLGwL3IzFfowb8YFhVKSsO9h1pgpmkCGOhxxqp2jh978nU6df3SdbPmEvPlZaoBsLDVqRMHUPOyDLbaPN6iQtdbRcQhhE+zRcHT8= # dev user name
    - secure: X1yp0ohu6eZyaw+ybLWYiyTYFemHBUDHeSb8g+SGPxRZRhqt8l/GwElRxwGzZOviPaJ4qwZ7jUUJHN1CPfbSahV3amTXQ1AhAn3g+hZyoqHc1BifuHYBY8rhfthvI1PjGAOT7vnZoD839Oxw4TMA5R/O9l6JT9GG5hGs8SDqOak= # dev password
    - secure: bxZ84spAuwVNcZFcaN5UW55nf+LIdcegGGlgXsOn4t2R+yimJt9f86v2euCZY0bs9drlJqHVGXF9KYiH32Y1eYchHx3J7oqUWWR5EFT3USAGkoOP3ZFmbdDJ6WCYkqTw/WtnVvLKRNDI6jaDQJf9+XgUafQGoHmZZx1Ocz8Ko1g= # stage password
    - secure: aHAXGNtzlkaNFdPlVGgJwi6HKzl5/7lv85CFxERypt4fvQCHtSYRrwVjEZMQiqwHOdXCrowV2+MMCjubT9w5A+i4iPVlOoz7iwdgmVYqxSzwpwlGqMFJGRH4H+8wDjbaTZRNYX8Ww7gOa32MtLTPjKQMh+kdgDgmi8zTOp2aZXQ= # stage user name
    - secure: Nsrtc48rxl4KORPc8pmodfyC0eKAGOuXuXLHhQ4m2yjOhq34Y3VkmfF5ScckZjq0o1nNilh+EJt4eCCdeVMppnp8ATlHGn6yW8AsgVJZeQforx+ywFLRvREvLY4UAbj8wTY0v7GyOiv2VKPbN9GvOLnelb69+qHWuv3Zc3AFNLo= # prod user name
    - secure: h+4hYf5Om0nqMChobBcpl0xHgBgWVylx+K+3igtEzmp2bpWXPYjY4iAbbc0JbuyVd41uqZz4G8PXfbpA0fyzy7cig0yy3I7GcDuyYbujtv4W2dFOtD3SrzgPTvfaPSLkp5PhOrFU0wR18ssTROHOOoK0bDkok5ZzKhPEUGlEN4Q= # prod password
before_script:
  - travis_retry pip install -U pip setuptools wheel
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements.test.txt
  - ". $HOME/.nvm/nvm.sh"
  - nvm install v7.7.4
  - nvm use v7.7.4
  - npm i -g npm
  - travis_retry npm install
  - npm run build
script:
  - py.test
  - npm run test-single
after_success:
  - travis_retry pip install bandit
  - bandit -r openfecwebapp *.py
  - travis_retry pip install codecov
  - codecov
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.25.0"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: invoke deploy --branch $TRAVIS_BRANCH --login True --yes
  on:
    all_branches: true
dd:
  secure: QkdjjW7fk4elNwOfduPMPLAv03WpyR1P65C0TiYhbZpOS0ONL1oRSaN4l+5dSvNG0wlinT3U7pBBsMaW+Pi+MH0+1ONbyc4eAF6ono4D4uaBvPq4zPe+y/y6TWCEiE+PrRvsXynvn6Hph8i2WHC9lbu4RzVhiQrvPaGJy6wY4kA=
